### ISSUE TITLE
NEW FAIR Reviews ontology

### ISSUE THREAD

**Issue by idafensp** [SPAROntologies/sparontologies.github.io#1]
**Name:** FAIR Reviews ontology

**Acronym:** fr

**Proponent(s):** [FAIR* Reviews](https://github.com/fairreviews)

The FAIR* Reviews ontology defines a set of classes, properties and axioms, for describing research reviews as semantic objects, reusing standard existing vocabularies using ontology engineering techniques.

**Comment by essepuntato** [comment]
Hi @idafensp,

Thanks for submitting!

I've just created the new repository [fr](https://github.com/SPAROntologies/fr) and listed the user "fairreviews" as admin. Please let me know if you would like me to add any other GitHub account as admin of the repo.

Have a nice day :-)
